//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VR_Web_Project.CreditCardWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditCardWS.CCServiceSoap")]
    public interface CCServiceSoap {
        
        // CODEGEN: Generating message contract since element name creditCardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Charge", ReplyAction="*")]
        VR_Web_Project.CreditCardWS.ChargeResponse Charge(VR_Web_Project.CreditCardWS.ChargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Charge", ReplyAction="*")]
        System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.ChargeResponse> ChargeAsync(VR_Web_Project.CreditCardWS.ChargeRequest request);
        
        // CODEGEN: Generating message contract since element name managerPassword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Credit", ReplyAction="*")]
        VR_Web_Project.CreditCardWS.CreditResponse Credit(VR_Web_Project.CreditCardWS.CreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Credit", ReplyAction="*")]
        System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.CreditResponse> CreditAsync(VR_Web_Project.CreditCardWS.CreditRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Charge", Namespace="http://tempuri.org/", Order=0)]
        public VR_Web_Project.CreditCardWS.ChargeRequestBody Body;
        
        public ChargeRequest() {
        }
        
        public ChargeRequest(VR_Web_Project.CreditCardWS.ChargeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string creditCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string expirationMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string expirationYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cvv;
        
        public ChargeRequestBody() {
        }
        
        public ChargeRequestBody(int price, string creditCardNumber, string expirationMonth, string expirationYear, string firstName, string lastName, string cvv) {
            this.price = price;
            this.creditCardNumber = creditCardNumber;
            this.expirationMonth = expirationMonth;
            this.expirationYear = expirationYear;
            this.firstName = firstName;
            this.lastName = lastName;
            this.cvv = cvv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeResponse", Namespace="http://tempuri.org/", Order=0)]
        public VR_Web_Project.CreditCardWS.ChargeResponseBody Body;
        
        public ChargeResponse() {
        }
        
        public ChargeResponse(VR_Web_Project.CreditCardWS.ChargeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChargeResult;
        
        public ChargeResponseBody() {
        }
        
        public ChargeResponseBody(bool ChargeResult) {
            this.ChargeResult = ChargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Credit", Namespace="http://tempuri.org/", Order=0)]
        public VR_Web_Project.CreditCardWS.CreditRequestBody Body;
        
        public CreditRequest() {
        }
        
        public CreditRequest(VR_Web_Project.CreditCardWS.CreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string managerPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int valueToBeAdded;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string creditCardNumber;
        
        public CreditRequestBody() {
        }
        
        public CreditRequestBody(string managerPassword, int valueToBeAdded, string creditCardNumber) {
            this.managerPassword = managerPassword;
            this.valueToBeAdded = valueToBeAdded;
            this.creditCardNumber = creditCardNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public VR_Web_Project.CreditCardWS.CreditResponseBody Body;
        
        public CreditResponse() {
        }
        
        public CreditResponse(VR_Web_Project.CreditCardWS.CreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreditResult;
        
        public CreditResponseBody() {
        }
        
        public CreditResponseBody(bool CreditResult) {
            this.CreditResult = CreditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCServiceSoapChannel : VR_Web_Project.CreditCardWS.CCServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCServiceSoapClient : System.ServiceModel.ClientBase<VR_Web_Project.CreditCardWS.CCServiceSoap>, VR_Web_Project.CreditCardWS.CCServiceSoap {
        
        public CCServiceSoapClient() {
        }
        
        public CCServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VR_Web_Project.CreditCardWS.ChargeResponse VR_Web_Project.CreditCardWS.CCServiceSoap.Charge(VR_Web_Project.CreditCardWS.ChargeRequest request) {
            return base.Channel.Charge(request);
        }
        
        public bool Charge(int price, string creditCardNumber, string expirationMonth, string expirationYear, string firstName, string lastName, string cvv) {
            VR_Web_Project.CreditCardWS.ChargeRequest inValue = new VR_Web_Project.CreditCardWS.ChargeRequest();
            inValue.Body = new VR_Web_Project.CreditCardWS.ChargeRequestBody();
            inValue.Body.price = price;
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.expirationMonth = expirationMonth;
            inValue.Body.expirationYear = expirationYear;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.cvv = cvv;
            VR_Web_Project.CreditCardWS.ChargeResponse retVal = ((VR_Web_Project.CreditCardWS.CCServiceSoap)(this)).Charge(inValue);
            return retVal.Body.ChargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.ChargeResponse> VR_Web_Project.CreditCardWS.CCServiceSoap.ChargeAsync(VR_Web_Project.CreditCardWS.ChargeRequest request) {
            return base.Channel.ChargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.ChargeResponse> ChargeAsync(int price, string creditCardNumber, string expirationMonth, string expirationYear, string firstName, string lastName, string cvv) {
            VR_Web_Project.CreditCardWS.ChargeRequest inValue = new VR_Web_Project.CreditCardWS.ChargeRequest();
            inValue.Body = new VR_Web_Project.CreditCardWS.ChargeRequestBody();
            inValue.Body.price = price;
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.expirationMonth = expirationMonth;
            inValue.Body.expirationYear = expirationYear;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.cvv = cvv;
            return ((VR_Web_Project.CreditCardWS.CCServiceSoap)(this)).ChargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VR_Web_Project.CreditCardWS.CreditResponse VR_Web_Project.CreditCardWS.CCServiceSoap.Credit(VR_Web_Project.CreditCardWS.CreditRequest request) {
            return base.Channel.Credit(request);
        }
        
        public bool Credit(string managerPassword, int valueToBeAdded, string creditCardNumber) {
            VR_Web_Project.CreditCardWS.CreditRequest inValue = new VR_Web_Project.CreditCardWS.CreditRequest();
            inValue.Body = new VR_Web_Project.CreditCardWS.CreditRequestBody();
            inValue.Body.managerPassword = managerPassword;
            inValue.Body.valueToBeAdded = valueToBeAdded;
            inValue.Body.creditCardNumber = creditCardNumber;
            VR_Web_Project.CreditCardWS.CreditResponse retVal = ((VR_Web_Project.CreditCardWS.CCServiceSoap)(this)).Credit(inValue);
            return retVal.Body.CreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.CreditResponse> VR_Web_Project.CreditCardWS.CCServiceSoap.CreditAsync(VR_Web_Project.CreditCardWS.CreditRequest request) {
            return base.Channel.CreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.CreditResponse> CreditAsync(string managerPassword, int valueToBeAdded, string creditCardNumber) {
            VR_Web_Project.CreditCardWS.CreditRequest inValue = new VR_Web_Project.CreditCardWS.CreditRequest();
            inValue.Body = new VR_Web_Project.CreditCardWS.CreditRequestBody();
            inValue.Body.managerPassword = managerPassword;
            inValue.Body.valueToBeAdded = valueToBeAdded;
            inValue.Body.creditCardNumber = creditCardNumber;
            return ((VR_Web_Project.CreditCardWS.CCServiceSoap)(this)).CreditAsync(inValue);
        }
    }
}
