//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VR_Web_Project.CreditCardWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditCardWS.CCServiceSoap")]
    public interface CCServiceSoap {
        
        // CODEGEN: Generating message contract since element name ccn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Charge", ReplyAction="*")]
        VR_Web_Project.CreditCardWS.ChargeResponse Charge(VR_Web_Project.CreditCardWS.ChargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Charge", ReplyAction="*")]
        System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.ChargeResponse> ChargeAsync(VR_Web_Project.CreditCardWS.ChargeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Charge", Namespace="http://tempuri.org/", Order=0)]
        public VR_Web_Project.CreditCardWS.ChargeRequestBody Body;
        
        public ChargeRequest() {
        }
        
        public ChargeRequest(VR_Web_Project.CreditCardWS.ChargeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ccn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string month;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ln;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cvv;
        
        public ChargeRequestBody() {
        }
        
        public ChargeRequestBody(int price, string ccn, string month, string year, string fn, string ln, string cvv) {
            this.price = price;
            this.ccn = ccn;
            this.month = month;
            this.year = year;
            this.fn = fn;
            this.ln = ln;
            this.cvv = cvv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeResponse", Namespace="http://tempuri.org/", Order=0)]
        public VR_Web_Project.CreditCardWS.ChargeResponseBody Body;
        
        public ChargeResponse() {
        }
        
        public ChargeResponse(VR_Web_Project.CreditCardWS.ChargeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChargeResult;
        
        public ChargeResponseBody() {
        }
        
        public ChargeResponseBody(bool ChargeResult) {
            this.ChargeResult = ChargeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCServiceSoapChannel : VR_Web_Project.CreditCardWS.CCServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCServiceSoapClient : System.ServiceModel.ClientBase<VR_Web_Project.CreditCardWS.CCServiceSoap>, VR_Web_Project.CreditCardWS.CCServiceSoap {
        
        public CCServiceSoapClient() {
        }
        
        public CCServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VR_Web_Project.CreditCardWS.ChargeResponse VR_Web_Project.CreditCardWS.CCServiceSoap.Charge(VR_Web_Project.CreditCardWS.ChargeRequest request) {
            return base.Channel.Charge(request);
        }
        
        public bool Charge(int price, string ccn, string month, string year, string fn, string ln, string cvv) {
            VR_Web_Project.CreditCardWS.ChargeRequest inValue = new VR_Web_Project.CreditCardWS.ChargeRequest();
            inValue.Body = new VR_Web_Project.CreditCardWS.ChargeRequestBody();
            inValue.Body.price = price;
            inValue.Body.ccn = ccn;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.fn = fn;
            inValue.Body.ln = ln;
            inValue.Body.cvv = cvv;
            VR_Web_Project.CreditCardWS.ChargeResponse retVal = ((VR_Web_Project.CreditCardWS.CCServiceSoap)(this)).Charge(inValue);
            return retVal.Body.ChargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.ChargeResponse> VR_Web_Project.CreditCardWS.CCServiceSoap.ChargeAsync(VR_Web_Project.CreditCardWS.ChargeRequest request) {
            return base.Channel.ChargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<VR_Web_Project.CreditCardWS.ChargeResponse> ChargeAsync(int price, string ccn, string month, string year, string fn, string ln, string cvv) {
            VR_Web_Project.CreditCardWS.ChargeRequest inValue = new VR_Web_Project.CreditCardWS.ChargeRequest();
            inValue.Body = new VR_Web_Project.CreditCardWS.ChargeRequestBody();
            inValue.Body.price = price;
            inValue.Body.ccn = ccn;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.fn = fn;
            inValue.Body.ln = ln;
            inValue.Body.cvv = cvv;
            return ((VR_Web_Project.CreditCardWS.CCServiceSoap)(this)).ChargeAsync(inValue);
        }
    }
}
